---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: dev
spec:
  encryptedData:
    API_KEY: AgB6ATlrFTYzE1HpCtOGoYHtbYzESOEuvIcI0wr7WDZ8ShpHh72A7hojBi/lgzAQWw9Vlq/Ml0/xaMgzciCUa95NxMw8PFEPC7mxMdJ+CMm68EXpCB0K1EbGpkUa7U/8Cie2i6GlRBqDN1TxogqvaG474KwrlCUHIqQIqhAkY/QVi+TFAFbIaOa7AUuHjWcb1WFJrzEcv2vqVsxt7lebzyjOq5/7JIu4A9yhkNYt90FqEIP3ndtPcepiWpsj33wmV03/WZoYhV1zvUVO0WzwQBTHEUdctz1sP0cZwJH6U+mXcEgAGt8a2UQ++kc4gfsZ8f/nLWy4jMK92JflNpLPjLo5+AmrPDMOGXkLlHh29iyH725Brfb3CztKNeiFr2AHMq9fer3OL0qtLXZlknCfKtwuwMHAxImvyyYKlZeautLOWz8Zr7KlY6JFv2C2805cpXU1bP3L+V8Qi3vQzGPpc25jZzsGd7uCxNbRQp+RJ2Oj0c/7WZLYW0rZqrpSnT6PJr4qC9RNjibkPRUnf9lyx3wsGCQbRoThNldVEB9Bqjg1V3Sd7gqz1rOriIfGDE28aLPgnhQ5DtcZv78/dRTAEdEmZKRFjs/a2Aqb4O8hwRG7amqhPIxQbTTuxZEey3W5D5F9fDUTrDVp1lR96GS5Qg0xQMHDY6ZY6xa2iv8FDYyJGf34/CnfnTM9SawaOmok2jxOAZ1NRiEeg2Tc
  template:
    metadata:
      name: my-secret
      namespace: dev
